"""add customer and khata_entry

Revision ID: 053a7408167c
Revises: 80c983944a9b
Create Date: 2026-07-16 16:18:54.375949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '053a7408167c'
down_revision: Union[str, Sequence[str], None] = '80c983944a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_name_unique', 'customer', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('khata_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('delta_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_khata_entry_customer_id'), 'khata_entry', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_khata_entry_customer_id'), table_name='khata_entry')
    op.drop_table('khata_entry')
    op.drop_index('ix_customer_name_unique', table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
