"""add bill and bill_item

Revision ID: 80c983944a9b
Revises: 85f3b8d56378
Create Date: 2026-07-16 12:53:09.513588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '80c983944a9b'
down_revision: Union[str, Sequence[str], None] = '85f3b8d56378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cgst_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sgst_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_chat_id'), 'bill', ['chat_id'], unique=False)
    op.create_index('ix_bill_chat_id_draft_unique', 'bill', ['chat_id'], unique=True, postgresql_where=sa.text("status = 'draft'"))
    op.create_table('bill_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit_price_at_sale', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gst_slab_at_sale', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_item_bill_id'), 'bill_item', ['bill_id'], unique=False)
    op.create_index(op.f('ix_bill_item_product_id'), 'bill_item', ['product_id'], unique=False)
    # plain ALTER TYPE INTEGER -> UUID has no implicit cast in postgres;
    # drop/re-add instead of USING, safe since reference_id is unused so far
    # (every existing row has it NULL -- verified before writing this).
    op.drop_column('stock_movement', 'reference_id')
    op.add_column('stock_movement', sa.Column('reference_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_stock_movement_reference_id_bill',
        'stock_movement', 'bill', ['reference_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_stock_movement_reference_id_bill', 'stock_movement', type_='foreignkey'
    )
    op.drop_column('stock_movement', 'reference_id')
    op.add_column('stock_movement', sa.Column('reference_id', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_bill_item_product_id'), table_name='bill_item')
    op.drop_index(op.f('ix_bill_item_bill_id'), table_name='bill_item')
    op.drop_table('bill_item')
    op.drop_index('ix_bill_chat_id_draft_unique', table_name='bill', postgresql_where=sa.text("status = 'draft'"))
    op.drop_index(op.f('ix_bill_chat_id'), table_name='bill')
    op.drop_table('bill')
    # ### end Alembic commands ###
